USE `medBot`;

INSERT INTO CaseReports (id, title, casereport, discussion, imageAddress) VALUES
(1, "Complex Germline K757N Mutation in Non-Small-Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase/case_report_section.txt", "images/LungCancer/lungcancercase/Discussion_1.txt", "images/LungCancer/lungcancercase/section_img_3_1.jpeg"),
(2, "Lung Cancer Mimicking Aspergilloma: A Case Report", "images/LungCancer/lungcancercase_2/case_report_section_2.txt", "images/LungCancer/lungcancercase_2/Discussion_2.txt", "images/LungCancer/lungcancercase_2/section_img_3_1.jpeg,images/LungCancer/lungcancercase_2/section_img_4_1.jpeg,images/LungCancer/lungcancercase_2/section_img_4_2.jpeg,images/LungCancer/lungcancercase_2/section_img_4_3.jpeg,images/LungCancer/lungcancercase_2/section_img_4_4.jpeg"),
(3, "Successful Treatment with Osimertinib Based on Therapeutic Drug Monitoring in a Hemodialysis Patient with Non-Small Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase_3/case_report_section_3.txt", "images/LungCancer/lungcancercase_3/Discussion_3.txt", "images/LungCancer/lungcancercase_3/section_img_4_2.jpeg"),
(4, "Durable Response to Maintenance Treatment Comprised of Viagenpumatucel-L, Nivolumab, Ramucirumab, and Docetaxel in a PD-L1-Low Advanced-Stage Non-Small-Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase_4/case_report_section_4.txt", "images/LungCancer/lungcancercase_4/Discussion_4.txt", "images/LungCancer/lungcancercase_4/section_img_4_1.jpeg, images/LungCancer/lungcancercase_4/section_img_5_1.jpeg"),
(5, "Complete Spontaneous Regression of Squamous-Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase_5/case_report_section_5.txt", "images/LungCancer/lungcancercase_5/Discussion_5.txt", "images/LungCancer/lungcancercase_5/section_img_3_1.jpeg, images/LungCancer/lungcancercase_5/section_img_4_1.jpeg"),
(6, "Stereotactic Body Radiotherapy in a transplanted lung for a primary lung cancer: Case Report", "images/LungCancer/lungcancercase_6/case_report_section_6.txt", "images/LungCancer/lungcancercase_6/Discussion_6.txt", "images/LungCancer/lungcancercase_6/section_img_9_1.jpeg, images/LungCancer/lungcancercase_6/section_img_10_1.jpeg, images/LungCancer/lungcancercase_6/section_img_11_1.jpeg"),
(7, "Diffuse Cystic Metastases in the Lung after Nivolumab Treatment in a Patient with Non-Small Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase_7/case_report_section_7.txt", "images/LungCancer/lungcancercase_7/Discussion_7.txt", "images/LungCancer/lungcancercase_7/section_img_2_1.jpeg, images/LungCancer/lungcancercase_7/section_img_3_1.jpeg, images/LungCancer/lungcancercase_7/section_img_3_2.jpeg"),
(8, "Erlotinib Achieved Partial Response in a Non-Small Cell Lung Cancer Patient with Gefitinib-Induced Interstitial Lung Disease", "images/LungCancer/lungcancercase_8/case_report_section_8.txt", "images/LungCancer/lungcancercase_8/Discussion_8.txt", "images/LungCancer/lungcancercase_8/section_img_3_2.jpeg"),
(9, "Different Response to Nivolumab in a Patient with Synchronous Double Primary Carcinomas of Hypopharyngeal Cancer and Non-Small-Cell Lung Cancer", "images/LungCancer/lungcancercase_9/case_report_section_9.txt", "images/LungCancer/lungcancercase_9/Discussion_9.txt", "images/LungCancer/lungcancercase_9/section_img_6_3.jpeg, images/LungCancer/lungcancercase_9/section_img_7_3.jpeg"),
(10, "Pulmonary Nocardiosis in a Non-Small Cell Lung Cancer Patient Being Treated for Pembrolizumab-Associated Pneumonitis", "images/LungCancer/lungcancercase_10/case_report_section_10.txt", "images/LungCancer/lungcancercase_10/Discussion_10.txt", "images/LungCancer/lungcancercase_10/section_img_3_1.png");


INSERT INTO colonCancer (id, title, casereport, imageAddress, diagnosis) VALUES
(1, "Presumed Solitary Dissemination of Colon Cancer Mimicking Primary Cancer of the Small Intestine", "images/ColonCancer/coloncancercase_1/case_report_section_1.txt", "images/ColonCancer/coloncancercase_1/section_img_3_1.jpeg, images/ColonCancer/coloncancercase_1/section_img_4_1.jpeg, images/ColonCancer/coloncancercase_1/section_img_5_1.jpeg","Recurrent peritoneal dissemination of rectal cancer mimicking primary small intestinal cancer."),
(2, "Metastatic Colon Cancer – An Effective Treatment Protocol of Integrative Therapies Including Electromagnetic Field Frequencies: A Case Report", "images/ColonCancer/coloncancercase_2/case_report_section_2.txt", "images/ColonCancer/coloncancercase_2/section_img_3_1.jpeg, images/ColonCancer/coloncancercase_2/section_img_8_1.jpeg, images/ColonCancer/coloncancercase_2/section_img_9_1.jpeg","Metastatic colonic adenocarcinoma (T4bN1M0, later progressing to stage IV with liver metastases)."),
(3, "Long-Term 5-Year Response to Pembrolizumab, Bevacizumab, and Capecitabine Regimen in a Metastatic Colon Cancer Patient with MSI-High and KRAS Mutation: Case Report", "images/ColonCancer/coloncancercase_3/case_report_section_3.txt", "images/ColonCancer/coloncancercase_3/section_img_4_1.jpeg, images/ColonCancer/coloncancercase_3/section_img_5_1.jpeg","Metastatic transverse colon adenocarcinoma (T3N1M1) with KRAS exon 2 mutation and MSI-H status"),
(4, "Early Detection of Circulating Tumor DNA Postoperatively Enables Discovery of Resectable Metastatic Disease in a Patient with Colon Cancer", "images/ColonCancer/coloncancercase_4/case_report_section_4.txt", "images/ColonCancer/coloncancercase_4/section_img_3_1.png, images/ColonCancer/coloncancercase_4/section_img_4_1.jpeg","stage IIA sigmoid colon adenocarcinoma with subsequent hepatic metastasis
"),
(5, "Pathological Complete Response of Clinical T4b Ascending Colon Cancer after Preoperative Chemotherapy Using Pembrolizumab", "images/ColonCancer/coloncancercase_5/case_report_section_5.txt", "images/ColonCancer/coloncancercase_5/section_img_3_1.jpeg, images/ColonCancer/coloncancercase_5/section_img_4_1.jpeg, images/ColonCancer/coloncancercase_5/section_img_4_2.jpeg, images/ColonCancer/coloncancercase_5/section_img_4_3.jpeg, images/ColonCancer/coloncancercase_5/section_img_5_1.jpeg, images/ColonCancer/coloncancercase_5/section_img_5_2.jpeg, images/ColonCancer/coloncancercase_5/section_img_6_1.jpeg","MSI-H ascending colon cancer
"),
(6, "Carcinoembryonic Antigen Elevation in a Patient with SARS-CoV-2 and a History of Colon Cancer", "images/ColonCancer/coloncancercase_7/case_report_section_7.txt", "images/ColonCancer/coloncancercase_7/section_img_2_1.jpeg, images/ColonCancer/coloncancercase_7/section_img_3_1.jpeg","Elevated carcinoembryonic antigen (CEA) level due to SARS-CoV-2 infection in a patient with a history of colon cancer."),
(7, "Weather the Cytokine Storm: A Report of Successful Management of a Colon Cancer Survivor and a Critically Ill Patient with COVID-19", "images/ColonCancer/coloncancercase_8/case_report_section_8.txt", "images/ColonCancer/coloncancercase_8/section_img_6_2.jpeg, images/ColonCancer/coloncancercase_8/section_img_6_3.jpeg","Severe COVID-19 with acute respiratory distress syndrome (ARDS) successfully treated with tocilizumab in a cancer survivor."),
(8, "Metachronous Mesorectal Recurrence after Colectomy for Ascending Colon Cancer", "images/ColonCancer/coloncancercase_9/case_report_section_9.txt", "images/ColonCancer/coloncancercase_9/section_img_3_1.jpeg, images/ColonCancer/coloncancercase_9/section_img_3_2.jpeg, images/ColonCancer/coloncancercase_9/section_img_4_1.jpeg","Isolated mesorectal recurrence of ascending colon adenocarcinoma following total abdominal colectomy with ileorectal anastomosis, likely due to retroperitoneal spread."),
(9, "Fatal Acute Liver Failure as a Consequence of Regorafenib Treatment in a Metastatic Colon Cancer", "images/ColonCancer/coloncancercase_10/case_report_section_10.txt", "images/ColonCancer/coloncancercase_10/section_img_5_3.jpeg","Severe acute hepatocellular insufficiency induced by regorafenib in a heavily pretreated metastatic colorectal cancer patient, leading to fatal hepatic failure.
");

INSERT INTO lungCancer (id, title, casereport, imageAddress, diagnosis) VALUES
(1, "Complex Germline K757N Mutation in Non-Small-Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase/case_report_section.txt", "images/LungCancer/lungcancercase/section_img_3_1.jpeg","Stage IV primary lung adenocarcinoma with a novel germline EGFR K757N mutation, resistant to TKI therapy, managed with chemoimmunotherapy.
"),
(2, "Lung Cancer Mimicking Aspergilloma: A Case Report", "images/LungCancer/lungcancercase_2/case_report_section_2.txt", "images/LungCancer/lungcancercase_2/section_img_3_1.jpeg,images/LungCancer/lungcancercase_2/section_img_4_1.jpeg,images/LungCancer/lungcancercase_2/section_img_4_2.jpeg,images/LungCancer/lungcancercase_2/section_img_4_3.jpeg,images/LungCancer/lungcancercase_2/section_img_4_4.jpeg","invasive adenosquamous carcinoma, initially misdiagnosed as aspergilloma."),
(3, "Successful Treatment with Osimertinib Based on Therapeutic Drug Monitoring in a Hemodialysis Patient with Non-Small Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase_3/case_report_section_3.txt", "images/LungCancer/lungcancercase_3/section_img_4_2.jpeg","GFR-mutated non-small cell lung cancer (NSCLC) with pleural dissemination, managed with osimertinib while undergoing hemodialysis."),
(4, "Durable Response to Maintenance Treatment Comprised of Viagenpumatucel-L, Nivolumab, Ramucirumab, and Docetaxel in a PD-L1-Low Advanced-Stage Non-Small-Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase_4/case_report_section_4.txt", "images/LungCancer/lungcancercase_4/section_img_4_1.jpeg, images/LungCancer/lungcancercase_4/section_img_5_1.jpeg","Stage 4A squamous NSCLC with low PD-L1, treated with a 4-drug regimen, achieving 28 months of disease stabilization before progression and death."),
(5, "Complete Spontaneous Regression of Squamous-Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase_5/case_report_section_5.txt", "images/LungCancer/lungcancercase_5/section_img_3_1.jpeg, images/LungCancer/lungcancercase_5/section_img_4_1.jpeg","Spontaneous regression of SCLC after biopsy in a 67-year-old female, possibly triggered by local trauma and immune response, with no relapse after 63 months."),
(6, "Stereotactic Body Radiotherapy in a transplanted lung for a primary lung cancer: Case Report", "images/LungCancer/lungcancercase_6/case_report_section_6.txt", "images/LungCancer/lungcancercase_6/section_img_9_1.jpeg, images/LungCancer/lungcancercase_6/section_img_10_1.jpeg, images/LungCancer/lungcancercase_6/section_img_11_1.jpeg","primary pulmonary adenocarcinoma (ADC) in a transplanted lung with EGFR exon 20 mutation and 40% PD-L1 expression, staged cT1bN0M0 (Stage IA2)."),
(7, "Diffuse Cystic Metastases in the Lung after Nivolumab Treatment in a Patient with Non-Small Cell Lung Cancer: A Case Report", "images/LungCancer/lungcancercase_7/case_report_section_7.txt", "images/LungCancer/lungcancercase_7/section_img_2_1.jpeg, images/LungCancer/lungcancercase_7/section_img_3_1.jpeg, images/LungCancer/lungcancercase_7/section_img_3_2.jpeg","recurrent lung adenocarcinoma with metastases, presenting as multiple cystic lung lesions after nivolumab treatment."),
(8, "Erlotinib Achieved Partial Response in a Non-Small Cell Lung Cancer Patient with Gefitinib-Induced Interstitial Lung Disease", "images/LungCancer/lungcancercase_8/case_report_section_8.txt", "images/LungCancer/lungcancercase_8/section_img_3_2.jpeg","stage IV lung adenocarcinoma complicated by EGFR-TKI-induced interstitial lung disease (ILD) after gefitinib treatment."),
(9, "Different Response to Nivolumab in a Patient with Synchronous Double Primary Carcinomas of Hypopharyngeal Cancer and Non-Small-Cell Lung Cancer", "images/LungCancer/lungcancercase_9/case_report_section_9.txt", "images/LungCancer/lungcancercase_9/section_img_6_3.jpeg, images/LungCancer/lungcancercase_9/section_img_7_3.jpeg,  double primary cancers","lung adenocarcinoma and hypopharyngeal squamous cell carcinoma (SCC), with differential responses to nivolumab based on the PD-L1 expression levels in each tumor."),
(10, "Pulmonary Nocardiosis in a Non-Small Cell Lung Cancer Patient Being Treated for Pembrolizumab-Associated Pneumonitis", "images/LungCancer/lungcancercase_10/case_report_section_10.txt", "images/LungCancer/lungcancercase_10/section_img_3_1.png","Nocardia cyriageorgica infection complicating immune checkpoint inhibitor (pembrolizumab)-induced pneumonitis in a patient with a history of non-small cell lung cancer and immunosuppression from corticosteroid treatment.");

INSERT INTO leukemia (id, title, casereport, imageAddress, diagnosis) VALUES 
(1, "Aleukemic Leukemia Cutis Manifesting with Disseminated Nodular Eruptions and a Plaque Preceding Acute Monocytic Leukemia: A Case Report", "images/Leukemia/leukemiacase_1/case_report_section_1.txt", "images/Leukemia/leukemiacase_1/section_img_5_2.jpeg, images/Leukemia/leukemiacase_1/section_img_6_2.jpeg, images/Leukemia/leukemiacase_1/section_img_7_2.jpeg"," Aleukemic leukemia cutis (ALC) presenting as acute monocytic leukemia (FAB AML-M5b)."),
(2, "Therapy-Related Leukemia following Docetaxel Chemotherapy for Metastatic Hormone-Sensitive Prostate Cancer: A Case Report", "images/Leukemia/leukemiacase_2/case_report_section_2.txt", "images/Leukemia/leukemiacase_2/section_img_3_1.jpeg, images/Leukemia/leukemiacase_2/section_img_4_1.jpeg, images/Leukemia/leukemiacase_2/section_img_5_1.jpeg","Therapy-related acute promyelocytic leukemia (t-APL) with t(15;17)(q22;q21) following docetaxel-based chemotherapy for metastatic hormone-sensitive prostate cancer (mHSPC)."),
(3, "Warm Autoimmune Hemolytic Anemia as First Presentation of Chronic Myeloid Leukemia: A Case Report", "images/Leukemia/leukemiacase_3/case_report_section_3.txt", "images/Leukemia/leukemiacase_3/section_img_4_1.jpeg, images/Leukemia/leukemiacase_3/section_img_4_2.jpeg, images/Leukemia/leukemiacase_3/section_img_4_3.jpeg","Chronic myeloid leukemia (CML) with concurrent autoimmune hemolytic anemia (AIHA)."),
(4, "A Patient with Acute Promyelocytic Leukemia Treated with Isotretinoin: A Case Report", "images/Leukemia/leukemiacase_4/case_report_section_4.txt", "images/Leukemia/leukemiacase_4/section_img_3_1.jpeg","Acute Promyelocytic Leukemia (APL) with Disseminated Intravascular Coagulation (DIC)."),
(5, "Therapy-Related Acute Myeloid Leukemia after CAR-T Cell Therapy with Brexucabtagene Autoleucel for Mantle Cell Lymphoma", "images/Leukemia/leukemiacase_5/case_report_section_5.txt", "images/Leukemia/leukemiacase_5/section_img_4_1.jpeg, images/Leukemia/leukemiacase_5/section_img_5_1.jpeg","Therapy-related acute erythroid leukemia (AML FAB M6) following CAR-T therapy for mantle cell lymphoma (MCL)."),
(6, "A Case of Hepatocellular Carcinoma after Treatment for Chronic Myeloid Leukemia in a Patient without Liver Disease", "images/Leukemia/leukemiacase_6/case_report_section_6.txt", "images/Leukemia/leukemiacase_6/section_img_4_1.jpeg, images/Leukemia/leukemiacase_6/section_img_5_1.jpeg, images/Leukemia/leukemiacase_6/section_img_6_1.jpeg","advanced hepatocellular carcinoma (HCC) with portal vein invasion in a patient with chronic myeloid leukemia (CML) on long-term imatinib therapy."),
(7, "Spontaneous Remission in a Patient with Chronic Myeloid Leukemia: A Case Report", "images/Leukemia/leukemiacase_7/case_report_section_7.txt", "images/Leukemia/leukemiacase_7/section_img_3_1.jpeg, images/Leukemia/leukemiacase_7/section_img_4_1.jpeg, images/Leukemia/leukemiacase_7/section_img_4_2.jpeg, images/Leukemia/leukemiacase_7/section_img_5_1.jpeg","Chronic Myelogenous Leukemia (CML) with spontaneous hematological and molecular remission."),
(8, "Negative Impact of Gemtuzumab Ozogamicin on CD33-Positive Early T-Cell Precursor Acute Lymphoblastic Leukemia: A Case Report", "images/Leukemia/leukemiacase_8/case_report_section_8.txt", "images/Leukemia/leukemiacase_8/section_img_4_1.jpeg","relapsed and refractory early T-cell precursor acute lymphoblastic leukemia (ETP-ALL)."),
(9, "Breast Cancer and Chronic Lymphocytic Leukemia and Renal Cell Carcinoma: A Case Report of a Rare Cancer Combination", "images/Leukemia/leukemiacase_9/case_report_section_9.txt", "images/Leukemia/leukemiacase_9/section_3_1.jpeg, images/Leukemia/leukemiacase_9/section_4_1.jpeg, images/Leukemia/leukemiacase_9/section_4_2.jpeg","chronic lymphocytic leukemia (B-CLL) with a secondary renal cell carcinoma (RCC)."),
(10, "Safety and Efficacy of Asciminib in Chronic Myeloid Leukemia Patient with Chronic Kidney Diseases: A Case Report", "images/Leukemia/leukemiacase_10/case_report_section_10.txt", "images/Leukemia/leukemiacase_10/section_img_4_1.jpeg","Chronic myelogenous leukemia (CML) with a history of type 2 diabetes, dyslipidemia, hypertension, and stage 3 chronic kidney disease.");

INSERT INTO brainTumor (id, title, casereport, imageAddress, diagnosis) VALUES
(1, "Difficulty Diagnosing a Brain Tumor during Clinical Maintenance of a Complete Response to anti-HER2 Treatments for Metastatic Breast Cancer: A Case Report", "images/BrainTumor/braintumorcase_1/case_report_section_1.txt", "images/BrainTumor/braintumorcase_1/section_img_2_1.jpeg, images/BrainTumor/braintumorcase_1/section_img_3_1.jpeg, images/BrainTumor/braintumorcase_1/section_img_3_2.jpeg, images/BrainTumor/braintumorcase_1/section_img_4_1.jpeg"," Stage IV HER2-positive invasive ductal carcinoma with metastatic progression, later diagnosed with primary central nervous system diffuse large B-cell lymphoma (DLBCL-CNS)."),
(2, "Targeted Radiotherapy of the Tumor Cavity after Surgical Resection of Aggressive Recurrent Brain Metastasis: A Case Report", "images/BrainTumor/braintumorcase_2/case_report_section_2.txt", "images/BrainTumor/braintumorcase_2/section_img_2_1.jpeg, images/BrainTumor/braintumorcase_2/section_img_3_1.jpeg"," Aggressive brain metastasis from grade 2 endometrial adenocarcinoma with rapid local recurrence, managed through two metastasectomies and targeted radiotherapy, achieving 2.5-year survival post-treatment."),
(3, "Malignant Phyllodes Tumor Presenting in Bone, Brain, Lungs, and Lymph Nodes", "images/BrainTumor/braintumorcase_3/case_report_section_3.txt", "images/BrainTumor/braintumorcase_3/section_img_5_3.jpeg, images/BrainTumor/braintumorcase_3/section_img_6_3.jpeg, images/BrainTumor/braintumorcase_3/section_img_7_3.jpeg, images/BrainTumor/braintumorcase_3/section_img_7_4.jpeg, images/BrainTumor/braintumorcase_3/section_img_8_3.jpeg, images/BrainTumor/braintumorcase_3/section_img_8_4.jpeg"," Metastatic malignant phyllodes tumor (PT) with spread to the spine, lungs, lymph nodes, and brain."),
(4, "Pulmonary Spindle Cell Carcinoma Presenting Anaplastic Lymphoma Kinase Rearrangement", "images/BrainTumor/braintumorcase_4/case_report_section_4.txt", "images/BrainTumor/braintumorcase_4/section_img_3_1.jpeg, images/BrainTumor/braintumorcase_4/section_img_4_1.jpeg, images/BrainTumor/braintumorcase_4/section_img_4_2.jpeg"," Primary pulmonary sarcomatoid carcinoma (PSC) with ALK rearrangement, metastatic to the brain, heart, adrenal glands, and bone."),
(5, "Isolated Leptomeningeal Progression in a Patient with NTRK Fusion+ Uterine Sarcoma: A Case Report", "images/BrainTumor/braintumorcase_5/case_report_section_5.txt", "images/BrainTumor/braintumorcase_5/section_img_3_1.jpeg, images/BrainTumor/braintumorcase_5/section_img_4_1.jpeg"," Leptomeningeal metastasis from NTRK3-SPECC1L fusion-positive undifferentiated uterine sarcoma, initially responsive to larotrectinib but ultimately progressing despite targeted therapy."),
(6, "CSF-ctDNA SMSEQ Analysis to Tailor the Treatment of a Patient with Brain Metastases: A Case Report", "images/BrainTumor/braintumorcase_6/case_report_section_6.txt", "images/BrainTumor/braintumorcase_6/section_img_5_3.jpeg, images/BrainTumor/braintumorcase_6/section_img_6_1.jpeg, images/BrainTumor/braintumorcase_6/section_img_6_4.jpeg"," Leptomeningeal metastasis from HER2-positive metastatic adenocarcinoma of unknown primary (CUP), successfully managed with a combination of anti-HER2 therapy and CSF-ctDNA-guided treatment."),
(7, "Infrared Thermography in Surgery of Newly Diagnosed Glioblastoma Multiforme: A Technical Case Report", "images/BrainTumor/braintumorcase_7/case_report_section_7.txt", "images/BrainTumor/braintumorcase_7/section_img_4_3.jpeg, images/BrainTumor/braintumorcase_7/section_img_5_1.jpeg, images/BrainTumor/braintumorcase_7/section_img_6_3.jpeg"," Right fronto-temporo-insular glioblastoma (GBM) detected using intraoperative infrared thermography (IRT) and 5-aminolevulinic acid fluorescence, successfully resected with no postoperative neurological deficits."),
(8, "Extracranial Metastases of a Cerebral Glioblastoma: A Case Report and Review of the Literature", "images/BrainTumor/braintumorcase_8/case_report_section_8.txt", "images/BrainTumor/braintumorcase_8/section_img_8_3.jpeg, images/BrainTumor/braintumorcase_8/section_img_9_2.jpeg, images/BrainTumor/braintumorcase_8/section_img_9_3.jpeg"," Glioblastoma (GBM) with extracranial metastases, patient succumbed to intracranial tumor progression 13 months after diagnosis."),
(9, "Efficacy of XELOX plus Bevacizumab in Brain Metastasis from Rectal Cancer", "images/BrainTumor/braintumorcase_9/case_report_section_9.txt", "images/BrainTumor/braintumorcase_9/section_img_4_1.jpeg, images/BrainTumor/braintumorcase_9/section_img_5_2.jpeg"," Metastatic colorectal cancer with hepatic and cerebellar metastases. Underwent BM resection and colostomy, followed by XELOX + bevacizumab, leading to tumor reduction and stable disease after 8 months."),
(10, "Bevacizumab is Effective for Recurrent Papillary Tumor of the Pineal Region: First Report", "images/BrainTumor/braintumorcase_10/case_report_section_10.txt", "images/BrainTumor/braintumorcase_10/section_img_4_1.jpeg, images/BrainTumor/braintumorcase_10/section_img_5_1.jpeg, images/BrainTumor/braintumorcase_10/section_img_6_1.jpeg, images/BrainTumor/braintumorcase_10/section_img_6_3.jpeg, images/BrainTumor/braintumorcase_10/section_img_7_1.jpeg"," Recurrent papillary tumor of the posterior fossa (PTPR) with multiple recurrences and metastases, successfully managed with bevacizumab and etoposide after failure of surgery, radiation, and chemotherapy.");